### ISSUE TITLE
Host puppetclass assignment results in error and broken class list

### ISSUE THREAD

**Issue by laugmanuel** [theforeman/foreman_puppet#132]
While editing a host and assigning puppet related configuration (puppetserver, environment, classes), the save fails with:
```
11:23:39 rails.1   | 2021-04-06T11:23:39 [I|app|0e511529] Started PATCH "/hosts/41" for ::1 at 2021-04-06 11:23:39 +0200
11:23:39 rails.1   | 2021-04-06T11:23:39 [I|app|0e511529] Processing by HostsController#update as */*
11:23:39 rails.1   | 2021-04-06T11:23:39 [I|app|0e511529]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"s6wHzWYI1dXVcg+acn1PQ1lHE4QTjBS/a+UI4nB2jqYZyBKV6OdWTQTDX9vHCHVG7Ud/F8BFAjq8s0LZuYFcHQ==", "host"=>{"name"=>"louis-tatem", "hostgroup_id"=>"", "puppet_attributes"=>{"environment_id"=>"1"}, "puppet_proxy_id"=>"1", "puppetclass_ids"=>["", "1"], "managed"=>"true", "progress_report_id"=>"[FILTERED]", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "mac"=>"aa:bb:cc:dd:ee:ff", "identifier"=>"", "name"=>"louis-tatem", "domain_id"=>"2", "subnet_id"=>"1", "ip"=>"", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "tag"=>"", "attached_to"=>"", "id"=>"41"}}, "architecture_id"=>"1", "operatingsystem_id"=>"1", "medium_id"=>"1", "ptable_id"=>"97", "pxe_loader"=>"", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"4-Users", "enabled"=>"1", "model_id"=>"", "expired_on"=>"", "comment"=>"", "overwrite"=>"false"}, "id"=>"41"}
11:23:39 rails.1   | 2021-04-06T11:23:39 [D|tax|0e511529] Current location set to Default Location
11:23:39 rails.1   | 2021-04-06T11:23:39 [D|tax|0e511529] Current organization set to Default Organization
11:23:39 rails.1   | 2021-04-06T11:23:39 [D|tax|0e511529] Current organization set to none
11:23:39 rails.1   | 2021-04-06T11:23:39 [D|tax|0e511529] Current location set to none
11:23:39 rails.1   | 2021-04-06T11:23:39 [D|app|0e511529] Unpermitted parameter: :puppet_attributes
11:23:39 rails.1   | 2021-04-06T11:23:39 [I|app|0e511529] Unable to suggest IP: subnet Subnet #1 don't have a DHCP proxy associated, a proxy is not in subnets organization or IPAM is not set to DHCP
11:23:39 rails.1   | 2021-04-06T11:23:39 [W|app|0e511529] Not queueing Nic::Managed: ["Environment with id 1 doesn't exist or is not assigned to proper organization and/or location"]
11:23:39 rails.1   | 2021-04-06T11:23:39 [W|app|0e511529] Not queueing Nic::Managed: ["Environment with id 1 doesn't exist or is not assigned to proper organization and/or location"]
11:23:39 rails.1   | 2021-04-06T11:23:39 [W|app|0e511529] Not queueing Nic::Managed: ["Environment with id 1 doesn't exist or is not assigned to proper organization and/or location"]
11:23:39 rails.1   | 2021-04-06T11:23:39 [E|app|0e511529] Failed to save: Environment with id 1 doesn't exist or is not assigned to proper organization and/or location
11:23:39 rails.1   | 2021-04-06T11:23:39 [I|app|0e511529]   Rendering hosts/edit.html.erb within layouts/application
11:23:39 rails.1   | 2021-04-06T11:23:39 [I|app|0e511529]   Rendered hosts/_progress.html.erb (Duration: 1.9ms | Allocations: 138)
11:23:39 rails.1   | 2021-04-06T11:23:39 [D|tax|0e511529] Current organization set to Default Organization
11:23:39 rails.1   | 2021-04-06T11:23:39 [D|tax|0e511529] Current location set to Default Location
[...]
11:23:40 rails.1   | 2021-04-06T11:23:40 [W|app|0e511529] user: Manuel.Laug
11:23:40 rails.1   |  0e511529 | PATCH /hosts/41
11:23:40 rails.1   |  0e511529 | AVOID eager loading detected
11:23:40 rails.1   |  0e511529 |   ForemanPuppet::Puppetclass => [:environment_classes]
11:23:40 rails.1   |  0e511529 |   Remove from your query: .includes([:environment_classes])
11:23:40 rails.1   |  0e511529 | Call stack
11:23:40 rails.1   |  0e511529 |   /Users/Manuel.Laug/_dev/_github/theforeman/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
11:23:40 rails.1   |  0e511529 |   /Users/Manuel.Laug/_dev/_github/theforeman/foreman/lib/foreman/middleware/catch_json_parse_errors.rb:9:in `call'
11:23:40 rails.1   |  0e511529 |   /Users/Manuel.Laug/_dev/_github/theforeman/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
11:23:40 rails.1   |  0e511529 |   /Users/Manuel.Laug/_dev/_github/theforeman/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
11:23:40 rails.1   |  0e511529 |
11:23:40 rails.1   |  0e511529 |
```

After that, the class seems to be associated (as seen in the screenshot and console), but deleting the class (using the *minus* button) does not work.
![image](https://user-images.githubusercontent.com/5444009/113690484-bdb1b680-96cb-11eb-8f7a-bbe636a2e38a.png)
```ruby
[2] pry(main)> Host.find_by(name: 'louis-tatem.lxsbx.example.com').classes
=> [#<ForemanPuppet::Puppetclass:0x00007fe4367d3a08 id: 1, name: "test", created_at: Tue, 06 Apr 2021 09:14:37 UTC +00:00, updated_at: Tue, 06 Apr 2021 09:14:37 UTC +00:00>]
```

We've used:

foreman develop branch (commit 744f9bd00597710883c6db1dfa37f3ca22cc18c5)
foreman_puppet master branch (commit fdeef1dc6febcfae22c8d3273cb18d6bdeb31a23)

**Comment by ezr-ondrej** [comment]
Just part of the issue was fixed.
