### ISSUE TITLE
Host creation using fact import fails with 500

### ISSUE THREAD

**Issue by laugmanuel** [theforeman/foreman_puppet#141]
I've tried to create a new host in Foreman using `POST` at `/api/hosts/facts`. This results in a `500 Internal server error`.

```log
13:13:29 rails.1   | 2021-05-14T13:13:29 [I|app|08484bdf] Started POST "/api/v2/hosts/facts" for ::1 at 2021-05-14 13:13:29 +0200
13:13:29 rails.1   | 2021-05-14T13:13:29 [I|app|08484bdf] Processing by Api::V2::HostsController#facts as JSON
13:13:29 rails.1   | 2021-05-14T13:13:29 [I|app|08484bdf]   Parameters: {"name"=>"test-host-2021-05-14-13-13-28-02b9", "facts"=>"[FILTERED]", "apiv"=>"v2", "host"=>{"name"=>"test-host-2021-05-14-13-13-28-02b9"}}
13:13:29 rails.1   | 2021-05-14T13:13:29 [D|app|08484bdf] Verifying request from ["localhost"] against ["localhost"]
13:13:29 rails.1   | 2021-05-14T13:13:29 [I|app|08484bdf] Import facts for 'test-host-2021-05-14-13-13-28-02b9' completed. Added: 431, Updated: 0, Deleted 0 facts
13:13:33 rails.1   | 2021-05-14T13:13:33 [I|aud|08484bdf] Nic::Managed (5) create event on mac
[...]
13:13:33 rails.1   | 2021-05-14T13:13:33 [I|aud|08484bdf] Nic::Managed (5) update event on name test-host-2021-05-14-13-13-28-02b9, test-host-2021-05-14-13-13-28-02b9.foo.example.local
13:13:33 rails.1   | 2021-05-14T13:13:33 [W|app|08484bdf] Action failed
13:13:33 rails.1   | 2021-05-14T13:13:33 [I|app|08484bdf] Backtrace for 'Action failed' error (NoMethodError): undefined method `environment' for #<Class:0x00007f975ced8e60>
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.4/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman_puppet/app/models/foreman_puppet/host_puppet_facet.rb:24:in `populate_fields_from_facts'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/concerns/facets/base_host_extensions.rb:26:in `block in populate_facet_fields'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/concerns/facets/base_host_extensions.rb:25:in `each'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/concerns/facets/base_host_extensions.rb:25:in `populate_facet_fields'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/host/managed.rb:506:in `populate_fields_from_facts'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/concerns/puppet_host_extensions.rb:3:in `populate_fields_from_facts'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:51:in `block (2 levels) in parse_facts'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/foreman/telemetry_helper.rb:27:in `telemetry_duration_histogram'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:50:in `block in parse_facts'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:91:in `block in skipping_orchestration'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/concerns/orchestration.rb:124:in `without_orchestration'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:90:in `skipping_orchestration'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:45:in `parse_facts'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:34:in `import_facts'
13:13:33 rails.1   |  08484bdf | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/controllers/api/v2/hosts_controller.rb:307:in `facts'
```

**Comment by laugmanuel** [comment]
The Hosts seem to get partially created; they do exist if I check using `rake console` but they are not visible in GUI.

**Comment by laugmanuel** [comment]
After starting with a clean database, I see the following error:
```log
16:10:10 rails.1   | 2021-05-14T16:10:10 [I|app|9d362c0a] Started POST "/api/v2/hosts/facts" for ::1 at 2021-05-14 16:10:10 +0200
16:10:11 rails.1   | 2021-05-14T16:10:11 [I|app|9d362c0a] Processing by Api::V2::HostsController#facts as JSON
16:10:11 rails.1   | 2021-05-14T16:10:11 [I|app|9d362c0a]   Parameters: {"name"=>"test-host-2021-05-14-16-10-10-424a", "facts"=>"[FILTERED]", "apiv"=>"v2", "host"=>{"name"=>"test-host-2021-05-14-16-10-10-424a"}}
16:10:11 rails.1   | 2021-05-14T16:10:11 [D|app|9d362c0a] Verifying request from ["localhost"] against ["localhost"]
16:10:11 rails.1   | 2021-05-14T16:10:11 [I|app|9d362c0a] Import facts for 'test-host-2021-05-14-16-10-10-424a' completed. Added: 43, Updated: 0, Deleted 0 facts
16:10:11 rails.1   | 2021-05-14T16:10:11 [I|aud|9d362c0a] Nic::Managed (3) create event on mac
[...]
16:10:11 rails.1   | 2021-05-14T16:10:11 [I|aud|9d362c0a] Host::Base (3) create event on build_errors
16:10:11 rails.1   | 2021-05-14T16:10:11 [D|tax|9d362c0a] Current location set to Default Location
16:10:11 rails.1   | 2021-05-14T16:10:11 [D|tax|9d362c0a] Current organization set to Default Organization
16:10:11 rails.1   | 2021-05-14T16:10:11 [W|app|9d362c0a] Action failed
16:10:11 rails.1   | 2021-05-14T16:10:11 [I|app|9d362c0a] Backtrace for 'Action failed' error (NoMethodError): undefined method `new' for nil:NilClass
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:47:in `block in parse_facts'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:90:in `block in skipping_orchestration'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/concerns/orchestration.rb:124:in `without_orchestration'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:89:in `skipping_orchestration'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:45:in `parse_facts'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/services/host_fact_importer.rb:34:in `import_facts'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/controllers/api/v2/hosts_controller.rb:307:in `facts'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/.rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/.rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.4/lib/abstract_controller/base.rb:195:in `process_action'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/.rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/.rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
16:10:11 rails.1   |  9d362c0a | /Users/Manuel.Laug/_dev/_github/theforeman/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
[...]
```

I'm wondering, if this should work at all or if I'm just seeing something we expect given on my input data?
I'll test this without this plugin and see what happens...

**Comment by ezr-ondrej** [comment]
It seems to be untested, as it was new method, I've introduced quite late. So totaly my fault.
#144 should fix this and is adding simple tests for it

**Comment by laugmanuel** [comment]
Hmm.. My import method seems to be broken as well. I'm hitting the same error in Foreman 2.5 without the plugin and a fresh database... I'll look into this more.
