### ISSUE TITLE
ENC no longer working after migration from 2.5.4 -> 3.0.1+foreman_puppet

### ISSUE THREAD

**Issue by jadestorm** [theforeman/foreman_puppet#229]
Hi folk!  Given the backtrace, this seems like the most likely place to discuss the cause of this.  I can no longer use my Foreman server as an ENC after I upgraded to 3.0.1.  What I get in the logs is:

```
2021-11-11T15:42:22 [I|app|5f4b1bec] Started GET "/node/XXXHOST?format=yml" for 10.50.61.64 at 2021-11-11 15:42:22 -0500
2021-11-11T15:42:22 [I|app|5f4b1bec] Processing by HostsController#externalNodes as YML
2021-11-11T15:42:22 [I|app|5f4b1bec]   Parameters: {"name"=>"XXXHOST"}
2021-11-11T15:42:22 [W|app|5f4b1bec] Failed to generate external nodes for XXXHOST
2021-11-11T15:42:22 [I|app|5f4b1bec] Backtrace for 'Failed to generate external nodes for XXXHOST' error (TypeError): no implicit conversion of nil into Array
 5f4b1bec | /usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/relation/delegation.rb:87:in `+'
 5f4b1bec | /usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/relation/delegation.rb:87:in `+'
 5f4b1bec | /usr/share/gems/gems/foreman_puppet-1.0.4/app/services/foreman_puppet/host_info_providers/config_groups_info.rb:7:in `host_info'
 5f4b1bec | /usr/share/foreman/app/models/concerns/host_info_extensions.rb:27:in `block in info'
 5f4b1bec | /usr/share/foreman/app/models/concerns/host_info_extensions.rb:25:in `each'
 5f4b1bec | /usr/share/foreman/app/models/concerns/host_info_extensions.rb:25:in `info'
 5f4b1bec | /usr/share/gems/gems/foreman_puppet-1.0.4/app/controllers/concerns/foreman_puppet/extensions/hosts_controller_extensions.rb:100:in `block in externalNodes'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/mime_responds.rb:205:in `respond_to'
 5f4b1bec | /usr/share/gems/gems/foreman_puppet-1.0.4/app/controllers/concerns/foreman_puppet/extensions/hosts_controller_extensions.rb:96:in `externalNodes'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
 5f4b1bec | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 5f4b1bec | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 5f4b1bec | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 5f4b1bec | /usr/share/gems/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 5f4b1bec | /usr/share/gems/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 5f4b1bec | /usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'
 5f4b1bec | /usr/share/gems/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'
 5f4b1bec | /usr/share/gems/gems/apipie-dsl-2.4.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 5f4b1bec | /usr/share/gems/gems/apipie-rails-0.5.17/lib/apipie/static_dispatcher.rb:66:in `call'
 5f4b1bec | /usr/share/gems/gems/apipie-rails-0.5.17/lib/apipie/extractor/recorder.rb:137:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 5f4b1bec | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 5f4b1bec | /usr/share/gems/gems/apipie-rails-0.5.17/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 5f4b1bec | /usr/share/foreman/lib/foreman/middleware/catch_json_parse_errors.rb:9:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
 5f4b1bec | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 5f4b1bec | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
 5f4b1bec | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:28:in `call'
 5f4b1bec | /usr/share/gems/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 5f4b1bec | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/request_id.rb:27:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
 5f4b1bec | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
 5f4b1bec | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
 5f4b1bec | /usr/share/gems/gems/secure_headers-6.3.0/lib/secure_headers/middleware.rb:11:in `call'
 5f4b1bec | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
 5f4b1bec | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `public_send'
 5f4b1bec | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `method_missing'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
 5f4b1bec | /usr/share/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
 5f4b1bec | /usr/share/gems/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
 5f4b1bec | /usr/share/gems/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
 5f4b1bec | /usr/share/gems/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
 5f4b1bec | /usr/share/gems/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
 5f4b1bec | /usr/share/gems/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
 5f4b1bec | /usr/share/gems/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
 5f4b1bec | /usr/share/gems/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2021-11-11T15:42:22 [I|app|5f4b1bec]   Rendering text template
2021-11-11T15:42:22 [I|app|5f4b1bec]   Rendered text template (Duration: 0.0ms | Allocations: 1)
2021-11-11T15:42:22 [I|app|5f4b1bec] Completed 412 Precondition Failed in 30ms (Views: 0.4ms | ActiveRecord: 9.0ms | Allocations: 8433)
```

Any ideas what might be causing this?  I've yet to be able to track down an actual cause, but to be fair I also haven't taken a dive into the plugin's code.

**Comment by jadestorm** [comment]
rubygem-foreman_puppet-1.0.4-1.fm3_0.el8.noarch
btw

**Comment by nadjaheitmann** [comment]
Has been fixed in https://github.com/theforeman/foreman_puppet/pull/209 (and now also cherry-picked)
