### ISSUE TITLE
Fix graphql issue in tests

### ISSUE THREAD

**Issue by Ron-Lavi** [theforeman/foreman_puppet#317]
failed run: https://github.com/theforeman/foreman_puppet/actions/runs/3521212077/jobs/5902845472#step:13:66

```
Error:
Queries::PuppetclassQueryTest#test_0001_fetching puppetclass attributes:
ActiveRecord::UnknownAttributeReference: Query method called with non-attribute argument(s): nil
    app/graphql/collection_loader.rb:44:in `preloader_for_association'
    app/graphql/collection_loader.rb:26:in `perform'
    test/test_helper.rb:187:in `block in <class:GraphQLQueryTestCase>'
    foreman_puppet/test/graphql/queries/puppetclass_query_test.rb:56:in `block in <class:PuppetclassQueryTest>'

Failure:
ForemanPuppet::Mutations::Hosts::CreateMutationTest#test_0001_creates a host with puppet parameters [/home/runner/work/foreman_puppet/foreman_puppet/foreman_puppet/test/graphql/mutations/hosts/create_mutation_test.rb:100]
Minitest::Assertion: Expected [{"message"=>"There can be only one input field named \"architectureId\"", "locations"=>[{"line"=>19, "column"=>17}, {"line"=>24, "column"=>17}], "path"=>["mutation createHostMutation", "createHost", "input"], "extensions"=>{"code"=>"inputFieldNotUnique", "name"=>"architectureId"}}] to be empty.
```

**Comment by Ron-Lavi** [comment]
Fixed by https://github.com/theforeman/foreman_puppet/pull/322
