### ISSUE TITLE
Changing puppet master for multiple hosts

### ISSUE THREAD

**Issue by gvde** [theforeman/foreman_puppet#333]
Taken from https://community.theforeman.org/t/changing-puppet-master-for-multiple-hosts/30946 and also in https://projects.theforeman.org/issues/35784

When I select multiple hosts and click on action “Change Puppet Master”, all I get is the modal with the circling image. I can see in the firefox dev tools that it calls the URI /foreman_puppet/hosts/select_multiple_puppet_proxy and gets 500 error.

foreman-3.5.1-1.el8.noarch
katello-4.7.2-1.el8.noarch
rubygem-foreman_puppet-5.0.0-1.fm3_5.el8.noarch
rubygem-hammer_cli_foreman_puppet-0.0.6-1.fm3_4.el8.noarch

Distribution and version:
Alma 8.7

```
2023-02-17T10:38:11 [I|app|ebb136fe] Started POST "/foreman_puppet/hosts/select_multiple_puppet_proxy" for x.x.x.x at 2023-02-17 10:38:11 +0100
2023-02-17T10:38:11 [I|app|ebb136fe] Processing by HostsController#select_multiple_puppet_proxy as HTML
2023-02-17T10:38:11 [I|app|ebb136fe]   Parameters: {"host_ids"=>["290", "291", "292", "293", "294"]}
2023-02-17T10:38:11 [I|app|ebb136fe]   Rendered hosts/select_multiple_puppet_proxy.html.erb within layouts/application (Duration: 265.1ms | Allocations: 32611)
2023-02-17T10:38:11 [I|app|ebb136fe]   Rendered layout layouts/application.html.erb (Duration: 265.4ms | Allocations: 32666)
2023-02-17T10:38:11 [W|app|ebb136fe] undefined method `update_multiple_puppet_proxy_hosts_path' for #<ActionView::Base:0x00000000599c00>
 ebb136fe | Did you mean?  update_multiple_puppet_ca_proxy_hosts_path
 ebb136fe |                update_multiple_puppet_ca_proxy_hosts_url
 ebb136fe |                update_multiple_owner_hosts_path
 ebb136fe |                update_multiple_power_state_hosts_path
 ebb136fe |                update_multiple_hostgroup_hosts_path
 ebb136fe |                update_multiple_parameters_hosts_path
 ebb136fe |                update_multiple_location_hosts_path
2023-02-17T10:38:11 [I|app|ebb136fe] Backtrace for 'undefined method `update_multiple_puppet_proxy_hosts_path' for #<ActionView::Base:0x00000000599c00>
 ebb136fe | Did you mean?  update_multiple_puppet_ca_proxy_hosts_path
 ebb136fe |                update_multiple_puppet_ca_proxy_hosts_url
 ebb136fe |                update_multiple_owner_hosts_path
 ebb136fe |                update_multiple_power_state_hosts_path
 ebb136fe |                update_multiple_hostgroup_hosts_path
 ebb136fe |                update_multiple_parameters_hosts_path
 ebb136fe |                update_multiple_location_hosts_path' error (ActionView::Template::Error): undefined method `update_multiple_puppet_proxy_hosts_path' for #<ActionView::Base:0x00000000599c00>
 ebb136fe | Did you mean?  update_multiple_puppet_ca_proxy_hosts_path
 ebb136fe |                update_multiple_puppet_ca_proxy_hosts_url
 ebb136fe |                update_multiple_owner_hosts_path
 ebb136fe |                update_multiple_power_state_hosts_path
 ebb136fe |                update_multiple_hostgroup_hosts_path
 ebb136fe |                update_multiple_parameters_hosts_path
 ebb136fe |                update_multiple_location_hosts_path
 ebb136fe | /usr/share/foreman/app/views/hosts/select_multiple_puppet_proxy.html.erb:3:in `_6988b89fc749e350262273d24cbe8d5a'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/base.rb:247:in `public_send'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/base.rb:247:in `_run'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/template.rb:154:in `block in render'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications.rb:205:in `instrument'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/template.rb:345:in `instrument_render_template'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/template.rb:152:in `render'
 ebb136fe | /usr/share/gems/gems/deface-1.5.3/lib/deface/action_view_extensions.rb:43:in `render'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/template_renderer.rb:11:in `render'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/rendering.rb:117:in `block in _render_template'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/base.rb:273:in `in_rendering_context'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/rendering.rb:116:in `_render_template'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/streaming.rb:218:in `_render_template'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/rendering.rb:103:in `render_to_body'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/abstract_controller/rendering.rb:25:in `render'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/rendering.rb:36:in `render'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
 ebb136fe | /usr/share/ruby/benchmark.rb:308:in `realtime'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/core_ext/benchmark.rb:14:in `ms'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
 ebb136fe | /usr/share/gems/gems/activerecord-6.1.7/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:45:in `render'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/abstract_controller/base.rb:228:in `process_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 ebb136fe | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 ebb136fe | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 ebb136fe | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 ebb136fe | /usr/share/gems/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 ebb136fe | /usr/share/gems/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 ebb136fe | /usr/share/gems/gems/activerecord-6.1.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/abstract_controller/base.rb:165:in `process'
 ebb136fe | /usr/share/gems/gems/actionview-6.1.7/lib/action_view/rendering.rb:39:in `process'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal.rb:190:in `dispatch'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_controller/metal.rb:254:in `dispatch'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `each'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `serve'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:842:in `call'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/engine.rb:539:in `call'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `public_send'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `method_missing'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/routing/mapper.rb:49:in `serve'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `each'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `serve'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:842:in `call'
 ebb136fe | /usr/share/gems/gems/katello-4.7.2/lib/katello/middleware/organization_created_enforcer.rb:18:in `call'
 ebb136fe | /usr/share/gems/gems/katello-4.7.2/lib/katello/middleware/event_daemon.rb:10:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
 ebb136fe | /usr/share/gems/gems/apipie-dsl-2.5.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 ebb136fe | /usr/share/gems/gems/apipie-rails-0.8.2/lib/apipie/static_dispatcher.rb:68:in `call'
 ebb136fe | /usr/share/gems/gems/apipie-rails-0.8.2/lib/apipie/extractor/recorder.rb:137:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
 ebb136fe | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 ebb136fe | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 ebb136fe | /usr/share/gems/gems/apipie-rails-0.8.2/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 ebb136fe | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/cookies.rb:689:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:98:in `run_callbacks'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/rack/logger.rb:37:in `call_app'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/rack/logger.rb:28:in `call'
 ebb136fe | /usr/share/gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 ebb136fe | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 ebb136fe | /usr/share/gems/gems/katello-4.7.2/lib/katello/prevent_json_parsing.rb:12:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
 ebb136fe | /usr/share/gems/gems/activesupport-6.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/ssl.rb:77:in `call'
 ebb136fe | /usr/share/gems/gems/actionpack-6.1.7/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 ebb136fe | /usr/share/gems/gems/secure_headers-6.5.0/lib/secure_headers/middleware.rb:11:in `call'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/engine.rb:539:in `call'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `public_send'
 ebb136fe | /usr/share/gems/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `method_missing'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/urlmap.rb:74:in `block in call'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/urlmap.rb:58:in `each'
 ebb136fe | /usr/share/gems/gems/rack-2.2.4/lib/rack/urlmap.rb:58:in `call'
 ebb136fe | /usr/share/gems/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
 ebb136fe | /usr/share/gems/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
 ebb136fe | /usr/share/gems/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 ebb136fe | /usr/share/gems/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
 ebb136fe | /usr/share/gems/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
 ebb136fe | /usr/share/gems/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
 ebb136fe | /usr/share/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2023-02-17T10:38:11 [I|app|ebb136fe]   Rendered common/500.html.erb (Duration: 2.2ms | Allocations: 875)
2023-02-17T10:38:11 [I|app|ebb136fe] Completed 500 Internal Server Error in 285ms (Views: 3.2ms | ActiveRecord: 4.7ms | Allocations: 39715)
```

**Comment by nadjaheitmann** [comment]
@Ron-Lavi I think this relates to https://github.com/theforeman/foreman_puppet/issues/330, doesn't it?

**Comment by Ron-Lavi** [comment]
Yeah, it looks like the same issue, closing for now
